/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package web_cat;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;

/**
 *
 * @author nawaz
 */
public class StopWords extends javax.swing.JFrame {

    /**
     * Creates new form StopWords
     */
    public StopWords() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Input_text = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Output_text = new javax.swing.JTextArea();
        Input_but = new javax.swing.JButton();
        Output_but = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1380, 780));

        Input_text.setColumns(20);
        Input_text.setRows(5);
        jScrollPane1.setViewportView(Input_text);

        Output_text.setColumns(20);
        Output_text.setRows(5);
        jScrollPane2.setViewportView(Output_text);

        Input_but.setText("Input");
        Input_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_butActionPerformed(evt);
            }
        });

        Output_but.setText("Output");
        Output_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output_butActionPerformed(evt);
            }
        });

        jLabel1.setText("Before Removing StopWords");

        jLabel2.setText("After Removing StopWords");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel3.setText("Removing Stop Words");

        jButton1.setText("NER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Input_but, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Output_but, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Input_but, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Output_but, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Output_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output_butActionPerformed
        // TODO add your handling code here:
        
     //   String[] list_stop = readStopWords("stop_words.txt");
        String stopWordsFilename = "stop_words.txt"; 
    
	String[] list_stops = null;
      String s;
        int numStopWords = 0; 
	
		
            try {
                BufferedReader stopWordsFile,wordfile,read = new BufferedReader(new InputStreamReader(System.in));
                stopWordsFile = new BufferedReader(new FileReader(stopWordsFilename));
                while((s=stopWordsFile.readLine())!=null)
                {
                   //System.out.println(numStopWords+" "+s);
                    ++numStopWords;
                }
               wordfile = new BufferedReader(new FileReader(stopWordsFilename));
		list_stops = new String[numStopWords];
                int i=0;
		while((s=wordfile.readLine())!=null)
                {
		   //System.out.println(s);
                    list_stops[i] = s;
               // System.out.println(list_stops[i]);
                i++;
                }
		stopWordsFile.close();
	    }
             catch (IOException ex) {
                Logger.getLogger(StopWords.class.getName()).log(Level.SEVERE, null, ex);
            }
         // System.out.println(list_stops.length);       
           try{
          Scanner fip1=new Scanner(new File("remove_symbols.txt"));
          FileOutputStream out=new FileOutputStream("stop.txt");
          PrintStream p =null;
        
        while(fip1.hasNextLine())
        {
           String temp = fip1.nextLine();
           System.out.println(temp);
            int flag=1;
            String[] newline = temp.split(" ");
            //String s1 = fip1.next();
            for(int k=0;k<newline.length;k++)
            {
                for(int i=0;i<numStopWords;i++)
                {
                if (newline[k].equals(list_stops[i])) {
                      flag=0;
                    //System.out.println(flag +" "+list_stops[i]+" "+newline[k]);
                  }
                }
                if(flag!=0)
           {
               p=new PrintStream(out);
                p.print(newline[k]+" ");  
               ///System.out.println(flag + newline[k]);
            }
                flag =1;
            }
           p.println("\n");
            
          
          //  String s1=fip1.next();
            //s1=s1.toLowerCase();
           /* int check = newline.length;
            for(int j=0;j<check;j++)
            {
               // System.out.println(newline[j]);
            for (int i=0;i<numStopWords;i++) {
                  //System.out.println(list_stops[i]);
                  if (newline[j].equals(list_stops[i])) {
                      flag=0;
                    System.out.println(list_stops[i]+" "+newline[j]);
                  }
                  
            }    
            
                 if(flag!=0)
            {
                System.out.println(newline[j]);
              p=new PrintStream(out);
                p.print(newline[j]+" "); 
                flag = 1;
                              
            }
              }
            p.println("\n");
           
          */
            }
         BufferedReader read = new BufferedReader(new FileReader("stop.txt"));
         Output_text.read(read,null);
         Output_text.requestFocus();
                   
        }
        catch(FileNotFoundException e){
            System.err.println("cannot read file");
        } catch (IOException ex) {
            Logger.getLogger(StopWords.class.getName()).log(Level.SEVERE, null, ex);
        } 
       
    }//GEN-LAST:event_Output_butActionPerformed

    private void Input_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_butActionPerformed
        try {
            // TODO add your handling code here:
            BufferedReader input_read = new BufferedReader(new FileReader("remove_symbols.txt"));
            Input_text.read(input_read, null);
            Input_text.requestFocus();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StopWords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(StopWords.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Input_butActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            NER ne = new NER();
            ne.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StopWords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Input_but;
    private javax.swing.JTextArea Input_text;
    private javax.swing.JButton Output_but;
    private javax.swing.JTextArea Output_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
